const profiles=[
{n:1,pos:['GK'],title:'THE LAST LINE',twin:'Gianluigi Buffon',players:['Iker Casillas','Manuel Neuer','Alisson'],reason:'The classic goalkeeper number — built for the player trusted with the final line.',base:[45,62,91,55]},
{n:2,pos:['DEF'],title:'THE LOCK',twin:'Cafu',players:['Gary Neville','Dani Carvajal','Kyle Walker'],reason:'A traditional defender’s shirt with modern attacking energy from the flank.',base:[70,67,88,79]},
{n:3,pos:['DEF'],title:'THE WALL',twin:'Paolo Maldini',players:['Ashley Cole','Roberto Carlos','Gerard Piqué'],reason:'A defensive classic associated with timing, composure and authority.',base:[61,72,94,75]},
{n:4,pos:['DEF','MID'],title:'THE COMMANDER',twin:'Sergio Ramos',players:['Virgil van Dijk','Patrick Vieira','Cesc Fàbregas'],reason:'A shirt for players who bring structure and presence through the heart of a team.',base:[66,76,93,82]},
{n:5,pos:['DEF','MID'],title:'THE ANCHOR',twin:'Carles Puyol',players:['Rio Ferdinand','Sergio Busquets','Zinedine Zidane'],reason:'Number 5 carries leadership history and suits the spine of the team.',base:[63,78,92,84]},
{n:6,pos:['DEF','MID'],title:'THE CONTROLLER',twin:'Xavi',players:['Bobby Moore','Thiago Alcântara','Franco Baresi'],reason:'A number linked with players who organise, connect and control the game.',base:[65,91,85,94]},
{n:7,pos:['WING','ST'],title:'THE GAME CHANGER',twin:'Cristiano Ronaldo',players:['David Beckham','Luís Figo','George Best'],reason:'One of football’s great attacking numbers — famous for wide threats, stars and match-winners.',base:[95,88,52,83]},
{n:8,pos:['MID'],title:'THE ENGINE',twin:'Steven Gerrard',players:['Andrés Iniesta','Frank Lampard','Toni Kroos'],reason:'The all-action midfield number: create, compete, arrive and influence everything.',base:[79,90,76,91]},
{n:9,pos:['ST'],title:'THE FINISHER',twin:'Ronaldo Nazário',players:['Robert Lewandowski','Erling Haaland','Karim Benzema'],reason:'The classic centre-forward shirt — direct, dangerous and associated with goals.',base:[94,69,45,72]},
{n:10,pos:['MID','WING','ST'],title:'THE MAGICIAN',twin:'Lionel Messi',players:['Diego Maradona','Ronaldinho','Pelé'],reason:'Football’s legendary creative number, associated with imagination and attacking freedom.',base:[91,98,43,98]},
{n:11,pos:['WING','ST'],title:'THE LIVEWIRE',twin:'Mohamed Salah',players:['Neymar','Didier Drogba','Ryan Giggs'],reason:'A fast attacking shirt traditionally at home on the wing or around the box.',base:[94,88,48,84]},
{n:14,pos:['MID','WING','ST'],title:'THE MAVERICK',twin:'Thierry Henry',players:['Johan Cruyff','Xabi Alonso','Javier Hernández'],reason:'An unconventional number made iconic by players who created their own identity.',base:[88,91,58,90]},
{n:17,pos:['MID','WING'],title:'THE SPARK',twin:'Kevin De Bruyne',players:['Nani','Alexis Sánchez','Marek Hamšík'],reason:'A modern creative number for someone who can change the rhythm of the game.',base:[85,94,61,93]},
{n:21,pos:['MID'],title:'THE CONNECTOR',twin:'Andrea Pirlo',players:['David Silva','Frenkie de Jong','Philipp Lahm'],reason:'A cultured midfield number associated with players who make difficult football look simple.',base:[68,95,70,97]},
{n:23,pos:['DEF','MID','WING'],title:'THE WILDCARD',twin:'David Beckham',players:['Jamie Carragher','Marco Materazzi','Shawky Gharib'],reason:'A less traditional shirt for players who like giving a familiar game their own identity.',base:[78,87,72,86]},
{n:30,pos:['WING','ST'],title:'THE PHENOMENON',twin:'Lionel Messi',players:['Benjamin Šeško','Nicolas Jackson'],reason:'A modern, unconventional attacking number with breakout-star energy.',base:[90,91,46,89]}
];
const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];let stream=null,scanTimer=null,position='MID',visualSeed=0;
function show(id){screens.forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.positions button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.positions button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');position=b.dataset.pos});
async function startCamera(){show('scanner');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:1280}},audio:false});$('#video').srcObject=stream;await $('#video').play();setTimeout(captureVisualSeed,900);$('#cameraLabel').textContent='FACE IN FRAME • HOLD STILL';$('#scanTitle').textContent='Scan ready';$('#scanText').textContent='Creating a local visual seed for your match';scanTimer=setTimeout(analyse,2300)}catch(e){$('#cameraLabel').textContent='CAMERA UNAVAILABLE';$('#scanTitle').textContent='Could not open camera';$('#scanText').textContent='Allow camera access, or use Try Without Camera.'}}
function captureVisualSeed(){try{const v=$('#video'),c=document.createElement('canvas');c.width=48;c.height=48;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0,48,48);const d=x.getImageData(0,0,48,48).data;let sum=0,contrast=0,last=0;for(let i=0;i<d.length;i+=16){const y=(d[i]+d[i+1]+d[i+2])/3;sum+=y;contrast+=Math.abs(y-last);last=y}visualSeed=Math.floor(sum+contrast)%10000}catch(e){visualSeed=Math.floor(Math.random()*10000)}}
function stopCamera(){clearTimeout(scanTimer);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function analyse(){stopCamera();show('analysing');$('#s2').classList.remove('on');$('#s3').classList.remove('on');setTimeout(()=>{$('#s2').classList.add('on');$('#s2').textContent='✓ '+position+' profile matched'},600);setTimeout(()=>{$('#s3').classList.add('on');$('#s3').textContent='✓ Jersey history matched'},1250);setTimeout(reveal,1850)}
function seeded(max,salt=1){const x=Math.sin((visualSeed+salt)*12.9898)*43758.5453;return Math.floor((x-Math.floor(x))*max)}
function reveal(){const pool=profiles.filter(p=>p.pos.includes(position));const pick=pool[seeded(pool.length,3)];const score=89+seeded(10,7);const labels=['ATTACK','CREATIVITY','DEFENCE','VISION'];const stats=pick.base.map((v,i)=>Math.max(40,Math.min(99,v-4+seeded(9,i+20))));$('#jerseyNumber').textContent=pick.n;$('#archetype').textContent=pick.title;$('#reasonText').textContent=pick.reason;$('#iconNumber').textContent=pick.n;$('#resultPos').textContent=position;$('#match').textContent=score+'% JERSEY MATCH';$('#twin').innerHTML=`<div class="twin-badge">#${pick.n}</div><div><b>${pick.twin}</b><small>PRO PLAYER MATCH</small></div>`;$('#players').innerHTML=pick.players.map(p=>`<span>${p}</span>`).join('');$('#stats').innerHTML=stats.map((v,i)=>`<div><b>${v}</b><small>${labels[i]}</small></div>`).join('');show('result');$('#meter').style.width='0';setTimeout(()=>$('#meter').style.width=score+'%',100)}
$('#startBtn').onclick=startCamera;$('#demoBtn').onclick=()=>{visualSeed=Math.floor(Math.random()*10000);analyse()};$('#cancelBtn').onclick=()=>{stopCamera();show('home')};$('#againBtn').onclick=startCamera;$('#changeBtn').onclick=()=>show('home');
$('#shareBtn').onclick=async()=>{const n=$('#jerseyNumber').textContent,t=$('#archetype').textContent,text=`JerseyScan matched me with #${n} — ${t}! ⚽ What's your number?`;try{if(navigator.share)await navigator.share({title:'My JerseyScan',text,url:location.href});else{await navigator.clipboard.writeText(text+' '+location.href);$('#shareBtn').textContent='✓ RESULT COPIED';setTimeout(()=>$('#shareBtn').textContent='↗ SHARE MY NUMBER',1800)}}catch(e){}};window.addEventListener('pagehide',stopCamera);