const profiles=[
{n:1,pos:['GK'],title:'THE LAST LINE',twin:'Gianluigi Buffon',players:['Iker Casillas','Manuel Neuer','Alisson'],reason:'The classic goalkeeper number — built for the player trusted with the final line.',base:[45,62,91,55]},
{n:2,pos:['DEF'],title:'THE LOCK',twin:'Cafu',players:['Gary Neville','Dani Carvajal','Kyle Walker'],reason:'A traditional defender’s shirt with modern attacking energy from the flank.',base:[70,67,88,79]},
{n:3,pos:['DEF'],title:'THE WALL',twin:'Paolo Maldini',players:['Ashley Cole','Roberto Carlos','Gerard Piqué'],reason:'A defensive classic associated with timing, composure and authority.',base:[61,72,94,75]},
{n:4,pos:['DEF','MID'],title:'THE COMMANDER',twin:'Sergio Ramos',players:['Virgil van Dijk','Patrick Vieira','Cesc Fàbregas'],reason:'A shirt for players who bring structure and presence through the heart of a team.',base:[66,76,93,82]},
{n:5,pos:['DEF','MID'],title:'THE ANCHOR',twin:'Carles Puyol',players:['Rio Ferdinand','Sergio Busquets','Zinedine Zidane'],reason:'Number 5 carries leadership history and suits the spine of the team.',base:[63,78,92,84]},
{n:6,pos:['DEF','MID'],title:'THE CONTROLLER',twin:'Xavi',players:['Bobby Moore','Thiago Alcântara','Franco Baresi'],reason:'A number linked with players who organise, connect and control the game.',base:[65,91,85,94]},
{n:7,pos:['WING','ST'],title:'THE GAME CHANGER',twin:'Cristiano Ronaldo',players:['David Beckham','Luís Figo','George Best'],reason:'One of football’s great attacking numbers — famous for wide threats, stars and match-winners.',base:[95,88,52,83]},
{n:8,pos:['MID'],title:'THE ENGINE',twin:'Steven Gerrard',players:['Andrés Iniesta','Frank Lampard','Toni Kroos'],reason:'The all-action midfield number: create, compete, arrive and influence everything.',base:[79,90,76,91]},
{n:9,pos:['ST'],title:'THE FINISHER',twin:'Ronaldo Nazário',players:['Robert Lewandowski','Erling Haaland','Karim Benzema'],reason:'The classic centre-forward shirt — direct, dangerous and associated with goals.',base:[94,69,45,72]},
{n:10,pos:['MID','WING','ST'],title:'THE MAGICIAN',twin:'Lionel Messi',players:['Diego Maradona','Ronaldinho','Pelé'],reason:'Football’s legendary creative number, associated with imagination and attacking freedom.',base:[91,98,43,98]},
{n:11,pos:['WING','ST'],title:'THE LIVEWIRE',twin:'Mohamed Salah',players:['Neymar','Didier Drogba','Ryan Giggs'],reason:'A fast attacking shirt traditionally at home on the wing or around the box.',base:[94,88,48,84]},
{n:12,pos:['GK','DEF'],title:'THE READY ONE',twin:'Marcelo',players:['John Obi Mikel','Olivier Giroud'],reason:'A versatile squad number for someone ready to step in and make an impact.',base:[67,72,82,73]},
{n:13,pos:['GK'],title:'THE ICE MAN',twin:'Thibaut Courtois',players:['Jan Oblak','David Ospina'],reason:'A goalkeeper number with cool-under-pressure energy.',base:[43,58,94,61]},
{n:14,pos:['MID','WING','ST'],title:'THE MAVERICK',twin:'Thierry Henry',players:['Johan Cruyff','Xabi Alonso','Javier Hernández'],reason:'An unconventional number made iconic by players who created their own identity.',base:[88,91,58,90]},
{n:15,pos:['DEF','MID'],title:'THE ENFORCER',twin:'Nemanja Vidić',players:['Mats Hummels','Alex Oxlade-Chamberlain'],reason:'A strong squad number for players who bring bite and balance.',base:[67,72,91,76]},
{n:16,pos:['GK','DEF','MID'],title:'THE UTILITY',twin:'Roy Keane',players:['Aaron Ramsey','Édouard Mendy'],reason:'A flexible number for the player who can solve different problems.',base:[69,80,84,83]},
{n:17,pos:['MID','WING'],title:'THE SPARK',twin:'Kevin De Bruyne',players:['Nani','Alexis Sánchez','Marek Hamšík'],reason:'A modern creative number for someone who can change the rhythm of the game.',base:[85,94,61,93]},
{n:18,pos:['MID','WING','ST'],title:'THE IMPACT',twin:'Paul Scholes',players:['Jordi Alba','Olivier Giroud'],reason:'A classic squad number with a habit of producing important moments.',base:[83,86,65,87]},
{n:19,pos:['MID','WING','ST'],title:'THE BREAKOUT',twin:'Sadio Mané',players:['Lionel Messi','Diego Costa'],reason:'A number with energetic, emerging-star history.',base:[89,87,56,85]},
{n:20,pos:['DEF','MID','WING'],title:'THE DYNAMO',twin:'Diogo Jota',players:['Deco','Bernardo Silva'],reason:'A flexible modern number for movement, invention and energy.',base:[84,90,68,88]},
{n:21,pos:['MID'],title:'THE CONNECTOR',twin:'Andrea Pirlo',players:['David Silva','Frenkie de Jong','Philipp Lahm'],reason:'A cultured midfield number associated with players who make difficult football look simple.',base:[68,95,70,97]},
{n:22,pos:['DEF','MID','WING'],title:'THE ROAMER',twin:'Kaká',players:['Ángel Di María','Jude Bellingham'],reason:'A number for players comfortable appearing wherever the game needs them.',base:[82,91,69,90]},
{n:23,pos:['DEF','MID','WING'],title:'THE WILDCARD',twin:'David Beckham',players:['Jamie Carragher','Marco Materazzi'],reason:'A less traditional shirt for players who give the game their own identity.',base:[78,87,72,86]},
{n:30,pos:['WING','ST'],title:'THE PHENOMENON',twin:'Lionel Messi',players:['Benjamin Šeško','Nicolas Jackson'],reason:'A modern, unconventional attacking number with breakout-star energy.',base:[90,91,46,89]}
];
const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];let stream=null,scanTimer=null,position='MID',visualSeed=0,mode='solo',currentResult=null;let squad=JSON.parse(localStorage.getItem('jerseySquad')||'[]');
function show(id){screens.forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function saveSquad(){localStorage.setItem('jerseySquad',JSON.stringify(squad));updateSquadUI()}
function updateSquadUI(){$('#squadCount').textContent=squad.length;$('#viewSquadBtn').classList.toggle('hidden',!squad.length||mode!=='squad')}
document.querySelectorAll('.positions button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.positions button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');position=b.dataset.pos});
document.querySelectorAll('.mode-tabs button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode-tabs button').forEach(x=>x.classList.toggle('selected',x===b));$('#squadSetup').classList.toggle('hidden',mode!=='squad');updateSquadUI()});
async function startCamera(){if(mode==='squad'&&!$('#playerName').value.trim()){$('#playerName').focus();$('#playerName').classList.add('error');setTimeout(()=>$('#playerName').classList.remove('error'),900);return}show('scanner');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:1280}},audio:false});$('#video').srcObject=stream;await $('#video').play();setTimeout(captureVisualSeed,900);$('#cameraLabel').textContent='FACE IN FRAME • HOLD STILL';$('#scanTitle').textContent='Scan ready';$('#scanText').textContent='Creating a local visual seed for your match';scanTimer=setTimeout(analyse,2300)}catch(e){$('#cameraLabel').textContent='CAMERA UNAVAILABLE';$('#scanTitle').textContent='Could not open camera';$('#scanText').textContent='Allow camera access, or use Try Without Camera.'}}
function captureVisualSeed(){try{const v=$('#video'),c=document.createElement('canvas');c.width=48;c.height=48;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0,48,48);const d=x.getImageData(0,0,48,48).data;let sum=0,contrast=0,last=0;for(let i=0;i<d.length;i+=16){const y=(d[i]+d[i+1]+d[i+2])/3;sum+=y;contrast+=Math.abs(y-last);last=y}visualSeed=Math.floor(sum+contrast)%10000}catch(e){visualSeed=Math.floor(Math.random()*10000)}}
function stopCamera(){clearTimeout(scanTimer);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function analyse(){stopCamera();show('analysing');$('#s2').classList.remove('on');$('#s3').classList.remove('on');setTimeout(()=>{$('#s2').classList.add('on');$('#s2').textContent='✓ '+position+' profile matched'},600);setTimeout(()=>{$('#s3').classList.add('on');$('#s3').textContent='✓ Jersey history matched'},1250);setTimeout(reveal,1850)}
function seeded(max,salt=1){const x=Math.sin((visualSeed+salt)*12.9898)*43758.5453;return Math.floor((x-Math.floor(x))*max)}
function reveal(){let pool=profiles.filter(p=>p.pos.includes(position));if(mode==='squad'){const used=new Set(squad.map(x=>x.n)),fresh=pool.filter(p=>!used.has(p.n));if(fresh.length)pool=fresh}const pick=pool[seeded(pool.length,3)],score=89+seeded(10,7),labels=['ATTACK','CREATIVITY','DEFENCE','VISION'],stats=pick.base.map((v,i)=>Math.max(40,Math.min(99,v-4+seeded(9,i+20))));const name=mode==='squad'?($('#playerName').value.trim()||`Player ${squad.length+1}`):'';currentResult={...pick,position,score,stats,name};if(mode==='squad'){squad.push({n:pick.n,title:pick.title,position,score,name});saveSquad()}$('#jerseyNumber').textContent=pick.n;$('#archetype').textContent=pick.title;$('#reasonText').textContent=pick.reason;$('#iconNumber').textContent=pick.n;$('#resultPos').textContent=position;$('#resultNameLabel').textContent=name?name.toUpperCase()+"'S NUMBER IS":'YOUR NUMBER IS';$('#match').textContent=score+'% JERSEY MATCH';$('#twin').innerHTML=`<div class="twin-badge">#${pick.n}</div><div><b>${pick.twin}</b><small>PRO PLAYER MATCH</small></div>`;$('#players').innerHTML=pick.players.map(p=>`<span>${p}</span>`).join('');$('#stats').innerHTML=stats.map((v,i)=>`<div><b>${v}</b><small>${labels[i]}</small></div>`).join('');$('#againBtn').textContent=mode==='squad'?'📷 SCAN NEXT SQUAD PLAYER':'📷 SCAN NEXT PLAYER';$('#squadResultBtn').classList.toggle('hidden',mode!=='squad');show('result');$('#meter').style.width='0';setTimeout(()=>$('#meter').style.width=score+'%',100)}
function renderSquad(){if(!squad.length){show('home');return}const order={GK:0,DEF:1,MID:2,WING:3,ST:4},rows={GK:[],DEF:[],MID:[],WING:[],ST:[]};squad.slice(0,11).forEach(p=>rows[p.position].push(p));let html='';Object.entries(rows).forEach(([pos,arr])=>arr.forEach((p,i)=>{const y={GK:88,DEF:69,MID:49,WING:27,ST:12}[pos],x=((i+1)/(arr.length+1))*100;html+=`<div class="pitch-player" style="left:${x}%;top:${y}%"><div class="shirt"><b>${p.n}</b></div><span>${escapeHtml(p.name)}</span><small>${pos}</small></div>`}));$('#pitchPlayers').innerHTML=html;const extra=squad.slice(11);$('#bench').innerHTML=extra.length?'<h3>BENCH</h3>'+extra.map(p=>`<span>#${p.n} ${escapeHtml(p.name)} · ${p.position}</span>`).join(''):'';$('#formationLabel').textContent=`${squad.length} PLAYER${squad.length===1?'':'S'} • UNIQUE NUMBERS`;show('squad')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function goAdd(){mode='squad';document.querySelectorAll('.mode-tabs button').forEach(x=>x.classList.toggle('selected',x.dataset.mode==='squad'));$('#squadSetup').classList.remove('hidden');$('#playerName').value='';show('home');updateSquadUI();setTimeout(()=>$('#playerName').focus(),250)}
$('#startBtn').onclick=startCamera;$('#demoBtn').onclick=()=>{if(mode==='squad'&&!$('#playerName').value.trim()){$('#playerName').focus();return}visualSeed=Math.floor(Math.random()*10000);analyse()};$('#cancelBtn').onclick=()=>{stopCamera();show('home')};$('#againBtn').onclick=()=>mode==='squad'?goAdd():startCamera();$('#changeBtn').onclick=()=>show('home');$('#viewSquadBtn').onclick=renderSquad;$('#squadResultBtn').onclick=renderSquad;$('#addPlayerBtn').onclick=goAdd;$('#resetSquadBtn').onclick=()=>{if(confirm('Reset the whole JerseyScan squad?')){squad=[];saveSquad();show('home')}};
$('#shareBtn').onclick=async()=>shareText(`JerseyScan matched me with #${$('#jerseyNumber').textContent} — ${$('#archetype').textContent}! ⚽`);$('#shareSquadBtn').onclick=async()=>shareText('Our JerseyScan squad ⚽\n'+squad.map(p=>`${p.name}: #${p.n} ${p.title}`).join('\n'));
async function shareText(text){try{if(navigator.share)await navigator.share({title:'JerseyScan',text,url:location.href});else{await navigator.clipboard.writeText(text+'\n'+location.href);alert('Copied to clipboard!')}}catch(e){}}
updateSquadUI();window.addEventListener('pagehide',stopCamera);