const numbers=[
{n:1,title:'THE LAST LINE',players:['Gianluigi Buffon','Iker Casillas','Manuel Neuer'],reason:'Calm presence, big-moment energy and the confidence to stand alone when the pressure is on.'},
{n:4,title:'THE COMMANDER',players:['Sergio Ramos','Virgil van Dijk','Patrick Vieira'],reason:'Strong, composed energy. Number 4 belongs to players who bring structure, presence and authority to the pitch.'},
{n:5,title:'THE ANCHOR',players:['Zinedine Zidane','Rio Ferdinand','Carles Puyol'],reason:'You give off composed, dependable energy — the kind of player a team can build around.'},
{n:6,title:'THE CONTROLLER',players:['Xavi','Thiago Alcântara','Bobby Moore'],reason:'Measured and intelligent. Number 6 is associated with players who read the game and keep everything connected.'},
{n:7,title:'THE GAME CHANGER',players:['Cristiano Ronaldo','David Beckham','Luís Figo','George Best'],reason:'Confident, expressive attacking energy. Number 7 is iconic for players who want the ball when something needs to happen.'},
{n:8,title:'THE ENGINE',players:['Steven Gerrard','Andrés Iniesta','Frank Lampard'],reason:'All-action energy. Number 8 suits players who influence everything — creating, competing and arriving when it matters.'},
{n:9,title:'THE FINISHER',players:['Ronaldo Nazário','Robert Lewandowski','Erling Haaland'],reason:'Direct and decisive. Number 9 is the classic shirt for someone who wants to turn chances into moments.'},
{n:10,title:'THE MAGICIAN',players:['Lionel Messi','Diego Maradona','Ronaldinho','Pelé'],reason:'Creative, expressive and impossible to ignore. Number 10 is football’s classic symbol of imagination and flair.'},
{n:11,title:'THE LIVEWIRE',players:['Neymar','Mohamed Salah','Didier Drogba'],reason:'Fast, adventurous energy. Number 11 fits players who stretch the game and make defenders uncomfortable.'},
{n:14,title:'THE MAVERICK',players:['Thierry Henry','Johan Cruyff','Xabi Alonso'],reason:'A less obvious number with huge football history — perfect for an individual who likes doing things differently.'},
{n:17,title:'THE SPARK',players:['Kevin De Bruyne','Nani','Alexis Sánchez'],reason:'Creative energy with a modern edge. Number 17 suits someone who can suddenly change the rhythm of a game.'},
{n:21,title:'THE CONNECTOR',players:['Andrea Pirlo','David Silva','Frenkie de Jong'],reason:'Smooth and thoughtful. Number 21 has been worn by players who make difficult football look simple.'},
{n:23,title:'THE WILDCARD',players:['David Beckham','Jamie Carragher','Marco Materazzi'],reason:'Bold and unconventional. Number 23 is for someone who enjoys making a familiar game feel like their own.'},
{n:30,title:'THE PHENOMENON',players:['Lionel Messi','Nicolas Jackson','Benjamin Šeško'],reason:'Young-energy meets headline potential. Number 30 feels unconventional, modern and ready to make its own history.'}
];
const $=s=>document.querySelector(s), screens=[...document.querySelectorAll('.screen')]; let stream=null,scanTimer=null;
function show(id){screens.forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
async function startCamera(){show('scanner');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:1280}},audio:false});$('#video').srcObject=stream;$('#cameraLabel').textContent='FACE DETECTED • HOLD STILL';$('#scanTitle').textContent='Face locked!';$('#scanText').textContent='Hold still while we capture your football vibe';scanTimer=setTimeout(analyse,2200)}catch(e){$('#cameraLabel').textContent='CAMERA UNAVAILABLE';$('#scanTitle').textContent='Could not open camera';$('#scanText').textContent='Allow camera access, or use Try Without Camera.'}}
function stopCamera(){clearTimeout(scanTimer);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function analyse(){stopCamera();show('analysing');$('#s2').classList.remove('on');$('#s3').classList.remove('on');setTimeout(()=>{$('#s2').classList.add('on');$('#s2').textContent='✓ Football energy matched'},650);setTimeout(()=>{$('#s3').classList.add('on');$('#s3').textContent='✓ Iconic number found'},1300);setTimeout(reveal,1950)}
function reveal(){const pick=numbers[Math.floor(Math.random()*numbers.length)],score=88+Math.floor(Math.random()*11);$('#jerseyNumber').textContent=pick.n;$('#archetype').textContent=pick.title;$('#reasonText').textContent=pick.reason;$('#iconNumber').textContent=pick.n;$('#match').textContent=score+'% VIBE MATCH';$('#players').innerHTML=pick.players.map(p=>`<span>${p}</span>`).join('');show('result');setTimeout(()=>$('#meter').style.width=score+'%',100)}
$('#startBtn').onclick=startCamera;$('#demoBtn').onclick=()=>{show('analysing');setTimeout(reveal,1700)};$('#cancelBtn').onclick=()=>{stopCamera();show('home')};$('#againBtn').onclick=startCamera;
$('#shareBtn').onclick=async()=>{const n=$('#jerseyNumber').textContent,t=$('#archetype').textContent,text=`JerseyScan gave me #${n} — ${t}! ⚽ What's your number?`;try{if(navigator.share)await navigator.share({title:'My JerseyScan',text,url:location.href});else{await navigator.clipboard.writeText(text+' '+location.href);$('#shareBtn').textContent='✓ RESULT COPIED';setTimeout(()=>$('#shareBtn').textContent='↗ SHARE MY NUMBER',1800)}}catch(e){}};
window.addEventListener('pagehide',stopCamera);